openapi: 3.1.0
info:
  title: Target Provider API
  version: 1.0.0
paths:
  /v1/job/agents/{agentId}/queue/achnowledge:
    post:
      summary: Acknowledge a job
      operationId: acknowledgeJob
      parameters:
        - name: agentId
          in: path
          required: true
          schema:
            type: string
          description: The agent ID
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                required:
                  - id

  /v1/job/agents/{agentId}/queue/next:
    get:
      summary: Get the next jobs
      operationId: getNextJobs
      parameters:
        - name: agentId
          in: path
          required: true
          schema:
            type: string
          description: The agent ID
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  jobExecution:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          description: The job ID
                        status:
                          type: string
                        jobAgentId:
                          type: string
                        jobAgentConfig:
                          type: object
                        message:
                          type: string
                        jobConfigId:
                          type: string
                      required:
                        - id
                        - status
                        - message
                        - jobConfigId
                        - jobAgentId
                        - jobAgentConfig
