name: Apps / API

on:
  workflow_dispatch:
  pull_request:
    branches: ["*"]
    paths:
      - apps/api/**
      - packages/**
      - .github/workflows/apps-api.yaml
      - pnpm-lock.yaml

  push:
    branches: ["main"]
    paths:
      - apps/api/**
      - packages/**
      - .github/workflows/apps-api.yaml
      - pnpm-lock.yaml

jobs:
  build:
    uses: ./.github/workflows/build-image.yaml
    secrets: inherit
    with:
      image-name: ctrlplane/api
      dockerfile: apps/api/Dockerfile
