name: Apps / Workspace Engine Router

on:
  pull_request:
    branches: ["*"]
    paths:
      - apps/workspace-engine-router/**
      - .github/workflows/apps-workspace-engine-router.yaml
  push:
    branches: ["main"]
    paths:
      - apps/workspace-engine-router/**
      - .github/workflows/apps-workspace-engine-router.yaml

jobs:
  build:
    uses: ./.github/workflows/build-image.yaml
    secrets: inherit
    with:
      image-name: ctrlplane/workspace-engine-router
      dockerfile: apps/workspace-engine-router/Dockerfile
      context: apps/workspace-engine-router
