name: Packages / Migrations

on:
  pull_request:
    branches: ["*"]
    paths:
      - packages/db/**
      - .github/workflows/packages-migrations.yaml
      - packages/validators/src/auth/index.ts
  push:
    branches: ["main"]
    paths:
      - packages/db/**
      - .github/workflows/packages-migrations.yaml
      - packages/validators/src/auth/index.ts

jobs:
  build:
    uses: ./.github/workflows/build-image.yaml
    secrets: inherit
    with:
      image-name: ctrlplane/migrations
      dockerfile: packages/db/Dockerfile
      platform: "linux/amd64"
